apiVersion: v1
kind: policy
metadata:
  name: hello-externaltraffic
spec:
  egress:
  - action: allow
    destination: {}
    source: {}
  ingress:
  - action: allow
    source:
     nets: [10.49.0.0/24, 10.48.0.0/24]
    destination: {}
  order: 400
  selector: calico/k8s_ns == 'default' && app == 'hello'
